# 4.3 유니버셜 함수

배열의 각 원소를 빠르게 처리하는 함수

In [1]:
import numpy as np

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# 각 원소의 제곱근 계산
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [3]:
# 각 원소에서 지수 ex를 계산
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

sqrt, exp 등은 1개의 매개변수를 취해서 단일 배열을 반환하는 단항 유니버셜 함수

2개의 매개변수를 취해서 단일 배열을 반환하는 함수는 이항 유니버셜 함수

In [5]:
# 이항 유니버셜 함수

rng = np.random.default_rng(seed=12345) # 난수생성

x = rng.standard_normal(8)

y = rng.standard_normal(8)

In [6]:
x

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331,
       -0.74088465, -1.3677927 ,  0.6488928 ])

In [7]:
y

array([ 0.36105811, -1.95286306,  2.34740965,  0.96849691, -0.75938718,
        0.90219827, -0.46695317, -0.06068952])

In [8]:
# 두 배열의 원소별 가장 큰 값 계산
np.maximum(x,y)

array([ 0.36105811,  1.26372846,  2.34740965,  0.96849691, -0.07534331,
        0.90219827, -0.46695317,  0.6488928 ])

여러 개의 배열을 반환하는 유니버셜 함수도 있다. ex) numpy.modf => 분수를 받아서 몫과 나머지를 함께 반환

In [10]:
arr2 = rng.standard_normal(7) # 난수 생성
arr2

array([-1.62158273, -0.15818926,  0.44948393, -1.34360107, -0.08168759,
        1.72473993,  2.61815943])

In [11]:
remainder, whole_part = np.modf(arr2)

In [12]:
remainder

array([-0.62158273, -0.15818926,  0.44948393, -0.34360107, -0.08168759,
        0.72473993,  0.61815943])

In [13]:
whole_part

array([-1., -0.,  0., -1., -0.,  1.,  2.])