# 4.6 선형대수

In [1]:
import numpy as np

In [2]:
x = np.array([[1.,2.,3.],[4.,5.,6.]])

y = np.array([[6.,23.],[-1,7],[8,9]])

In [3]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [5]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [6]:
# x.dot(y)는 np.dot(x,y) 와 동일

np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [7]:
# 2차원 배열과 곱셈이 가능한 크기의 1차원 배열 간의 행렬 곱셈의 결과는 1차원 배열
ones = np.ones(3)

In [8]:
np.dot(x,ones)

array([ 6., 15.])

In [9]:
x @ np.ones(3)

array([ 6., 15.])

numpy.linalg 는 행렬의 분할, 역행렬, 행렬식과 같은 것을 포함

In [10]:
from numpy.linalg import inv, qr

rng = np.random.default_rng(seed = 12345)
k = rng.standard_normal((5,5))

In [11]:
mat = k.T @ k
inv(mat)

array([[ 0.15548538, -0.36723081, -0.52638547, -0.2300642 , -0.04646089],
       [-0.36723081,  2.54917814,  3.47827334,  1.48196722,  0.22206454],
       [-0.52638547,  3.47827334,  5.46389554,  2.46214396,  0.63467543],
       [-0.2300642 ,  1.48196722,  2.46214396,  1.38302896,  0.33430132],
       [-0.04646089,  0.22206454,  0.63467543,  0.33430132,  0.33879566]])

In [12]:
mat @ inv(mat)

array([[ 1.00000000e+00,  4.99285027e-17, -2.32472626e-16,
        -2.35388056e-16, -1.12575057e-18],
       [ 1.55867966e-16,  1.00000000e+00,  9.98311990e-17,
        -1.96348091e-16, -3.86511231e-16],
       [-6.92418622e-17, -7.91606813e-16,  1.00000000e+00,
         5.64803789e-16,  1.61057761e-16],
       [-2.37101845e-16,  1.84817406e-15,  3.81257497e-15,
         1.00000000e+00,  3.71349003e-16],
       [ 9.72642079e-17,  2.31009855e-16, -7.19939179e-17,
        -4.80724193e-16,  1.00000000e+00]])